name: gym-tracker

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: gym-tracker-sql
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gym-tracker-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # NestJS API
  api:
    build:
      context: ../api
      dockerfile: Dockerfile
    container_name: gym-tracker-api
    restart: unless-stopped
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DIRECT_URL=${DIRECT_URL}
      - FRONTEND_URL=${FRONTEND_URL}
      - PORT=4000
      - APP_TIMEZONE=${APP_TIMEZONE:-America/Lima}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - gym-tracker-network

  # Next.js Frontend
  web:
    build:
      context: ../web
      dockerfile: Dockerfile
      args:
        API_INTERNAL_URL: http://api:4000
    container_name: gym-tracker-web
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - API_INTERNAL_URL=http://api:4000
    depends_on:
      - api
    networks:
      - gym-tracker-network

volumes:
  postgres_data:


networks:
  gym-tracker-network:
    driver: bridge
