name: gym-tracker-dev

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: gym-tracker-dev-sql
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - gym-tracker-dev-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # NestJS API
  api:
    build:
      context: ../../api
      dockerfile: Dockerfile
    container_name: gym-tracker-dev-api
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - DIRECT_URL=${DIRECT_URL}
      - FRONTEND_URL=${FRONTEND_URL}
      - JWT_SECRET=${JWT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - PORT=4000
    ports:
      - "4000:4000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - gym-tracker-dev-network

  # Next.js Frontend
  web:
    build:
      context: ../../web
      dockerfile: Dockerfile
      args:
        API_INTERNAL_URL: http://api:4000
        NEXT_PUBLIC_GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
    container_name: gym-tracker-dev-web
    restart: unless-stopped
    environment:
      - API_INTERNAL_URL=http://api:4000
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - gym-tracker-dev-network

  # Cloudflare Tunnel
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: gym-tracker-tunnel
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    depends_on:
      - web
    networks:
      - gym-tracker-dev-network

volumes:
  postgres_data_dev:


networks:
  gym-tracker-dev-network:
    driver: bridge
